#ifndef ENUMS_NORM_TYPE_HPP
#define ENUMS_NORM_TYPE_HPP

enum NormType {
	NONE = -1,
	NORMAL_MAP_01,
	NORMAL_MAP_02,
	NORMAL_MAP_03,
	NORMAL_MAP_04,
	NORMAL_MAP_05,
	NORMAL_MAP_06,
	NORMAL_MAP_07,
	NORMAL_MAP_08,
	NORMAL_MAP_09,
	NORMAL_MAP_10
};

#endif